### PR TITLE
Please try this

### PR DESCRIPTION
**Pull request by tlienart**
1. automatic deployment via GitHub action (don't use `publish`, because in this case things are within your `doc/` folder, anyway just push changes to the repo and the action will do the rest, this is the recommended way of doing things, `publish` is obsolete)
2. use of double braces in maths is prohibited, you had a few `{{i}}` in this case it should be just `{i}` otherwise just add whitespace between double braces so for instance `{ {` and `} }`. 

I hope this works.

### CODE REVIEW

**Comment by joseph-pollacco** [comment]
Dear Thibaut Lienart,

Thanks for all your kindness, I performed all the corrections manually as I am not too familiar with pull request. 
I was impressed that you took the trouble to correct our equations, thank for your kindness.

I also build doc from scratch. But it did not seem to have solved the issues;

Please look at:
https://manaakiwhenua.github.io/SoilWater_ToolBox.jl/

Also kindly look at:
https://manaakiwhenua.github.io/SoilWater_ToolBox.jl/HyPix/HyPix_Output

I also changed the name of the SoilWater_ToolBox to SoilWater_ToolBox.jl

Kind regards,
Joseph

**Comment by tlienart** [comment]
It would have been much easier for you to just merge the pull request, I actually still encourage you to do so.

You did not add the GitHub deploy script and so the rest of the fixes won't matter, you're still not deploying the site correctly because the proper folder is not getting pushed in the right place

**Comment by tlienart** [comment]
Ok here's an easier path:

this repository is fully working and basically a copy of what I did with a few changes: https://github.com/tlienart/demo-soilwater.jl

output:

* https://tlienart.github.io/demo-soilwater.jl/SoilWater_ToolBox/HyPix/HyPix_Output/index.html

observe that I do not use `publish`, I only pushed changes to GitHub and the GitHub action (this script: https://github.com/tlienart/demo-soilwater.jl/blob/main/.github/workflows/deploy.yml) gets automatically triggered and pushes the relevant files to the `gh-pages` branch which allows the site to be deployed properly)

what you can do now:

* clone my repository
* replace *your* `doc/` with mine from the cloned repository
* copy the `.github` folder from the cloned repository to your folder (it **must** be at the top level like here: 

Screenshot 2022-03-31 at 09 05 07

* push the changes to GitHub

this should automatically trigger an action which does the rest. In the screenshot above note the green checkmark top-right; when you push this is first a yellow circle then becomes a green checkmark when everything went fine.

**Comment by tlienart** [comment]
for some reason you had selected the branch `gh-pages` with folder `docs` (which doesn't exist), that's why your builds failed; it should have been just `gh-pages`. Now fixed.

**Pull request closed without merging**
